#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Nov 11 13:08:45 IST 2016
apiSecret=b929f22a144f2feff80470ab876291b4a8c4f68d42198289e01d7a62e63679fd
