AUTH_USER=support@myaccounts.in
AUTH_PASSWORD=support8842
RECEPENTS=ghanashyam.b@myaccounts.in
SUBJECT=My TaskManagement Crash Report

//msivan@myaccounts.in,subbarao@myaccounts.in,venu@myaccounts.in,srikanth@myaccounts.in